stages:
  - validation

validate-all:
  stage: validation
  image: node:14-alpine
  script:
    - npm i pnpm -g
    - pnpm install
    - pnpm run lbt --prefix shared
    - pnpm run lbt --prefix backend
    - pnpm run lbt --prefix simulator

