stages:
  - validating-shared
  - validating-apps

shared:
  stage: validating-shared
  image: node:14-alpine
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - cd shared
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov

backend:
  stage: validating-apps
  image: node:14-alpine
  only: ["branches", "tags"]
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - cd shared && npm ci && npm run build && cd ..
    - cd backend
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov

backend-e2e:
  stage: validating-apps
  image: node:14-alpine
  only: ["master"]
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - cd shared && npm ci && npm run build && cd ..
    - cd backend
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov

simulator:
  stage: validating-apps
  image: node:14-alpine
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - cd shared && npm ci && npm run build && cd ..
    - cd simulator
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov
