stages:
  - validating-shared
  - validating-apps

shared:
  stage: validating-shared
  image: node:14-alpine
  script:
    - cd shared
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov

backend:
  stage: validating-apps
  image: node:14-alpine
  except:
    refs:
      - master
  script:
    - cd shared && npm ci && npm run build && cd ..
    - cd backend
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov

backend-with-e2e:
  stage: validating-apps
  image: node:14-alpine
  only:
    refs:
      - master
  script:
    - cd shared && npm ci && npm run build && cd ..
    - cd backend
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov
    - npm run test:e2e

simulator:
  stage: validating-apps
  image: node:14-alpine
  script:
    - cd shared && npm ci && npm run build && cd ..
    - cd simulator
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov
