stages:
  - validation

validate-all:
  stage: validation
  image: node:14-alpine
  script:
    - echo "*** shared ***"
    - cd shared
    - npm ci
    - npm run lint
    - npm run build
    - npm run test
    - npm pack
    - npm run share
    - cd ..

    - echo "*** backend ***"
    - cd backend
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov
    - npm run test:e2e
    - cd ..

    - echo "*** simulator ***"
    - cd simulator
    - npm ci
    - npm run lint
    - npm run build
    - npm run test
    - cd ..
