stages:
  - validation

validate-all:
  stage: validation
  image: node:14-alpine
  script:
    - npm i pnpm -g
    - pnpm install

    - cd common-lib
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd ocpp-lib
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd backend-lib
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd backend-core
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - pnpm run test:e2e
    - cd ..

    - cd backend-ui
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd charging-station-lib
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd charging-station-ui
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd charging-station-cli
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..
