stages:
  - validation

validate-all:
  stage: validation
  image: node:14-alpine
  script:
    - echo "*** shared ***"
    - npm --prefix shared ci
    - npm --prefix shared run lint
    - npm --prefix shared run build
    - npm --prefix shared run test

    - echo "*** backend ***"
    - npm --prefix backend ci
    - npm --prefix backend run lint
    - npm --prefix backend run build
    - npm --prefix backend run test:cov
    - npm --prefix backend run test:e2e

    - echo "*** simulator ***"
    - npm --prefix simulator ci
    - npm --prefix simulator run lint
    - npm --prefix simulator run build
    - npm --prefix simulator run test
