stages:
  - validation
  - utils

.shared:
  stage: validation
  image: $CI_REGISTRY_IMAGE:pipeline
  except:
    - web
  script:
    - pnpm install
    - pnpm --prefix shared run lbt

.backend:
  stage: validation
  image: $CI_REGISTRY_IMAGE:pipeline
  except:
    - web
  script:
    - pnpm install
    - pnpm --prefix shared run build
    - pnpm --prefix backend run lbt

simulator:
  stage: validation
  image: $CI_REGISTRY_IMAGE:pipeline
  except:
    - web
  script:
    - pwd
    - ls -la /
    - mount
    - ls -la
    - ls -la /builds/YellowGarbageBag
    - ls -la /builds/YellowGarbageBag/csms
    - echo foo
    - pnpm install
    - pnpm --prefix shared run build
    - pnpm --prefix simulator run lbt

create-pipeline-image:
  stage: utils
  image: docker:19
  services:
    - docker:19-dind
  only:
    refs:
      - web
    variables:
      - $docker == "build"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:pipeline || true
    - docker build
      --cache-from $CI_REGISTRY_IMAGE:pipeline
      --tag $CI_REGISTRY_IMAGE:pipeline
      --file Dockerfile-pipeline .
    - docker push $CI_REGISTRY_IMAGE:pipeline
