stages:
  - validation
  - utils

.shared:
  stage: validation
  image: $CI_REGISTRY_IMAGE:pipeline
  except:
    - web
  script:
    - cd shared
    - pnpm install
    - pnpm run lint
    - pnpm run build
    - pnpm run test

backend:
  stage: validation
  image: $CI_REGISTRY_IMAGE:pipeline
  except:
    - web
  script:
    - cd backend
    - pnpm install
    - ls -la node_modules/
    - ls -la /.pnpm-store/
    - pnpm run lint
    - pnpm run build
    - pnpm run test:cov
    - pnpm run test:e2e

.simulator:
  stage: validation
  image: $CI_REGISTRY_IMAGE:pipeline
  except:
    - web
  script:
    - cd simulator
    - pnpm install
    - pnpm run lint
    - pnpm run build
    - pnpm run test

create-pipeline-image:
  stage: utils
  image: docker:19
  services:
    - docker:19-dind
  only:
    refs:
      - web
    variables:
      - $docker == "build"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:pipeline || true
    - docker build
      --cache-from $CI_REGISTRY_IMAGE:pipeline
      --tag $CI_REGISTRY_IMAGE:pipeline
      --file Dockerfile-pipeline .
    - docker push $CI_REGISTRY_IMAGE:pipeline
