stages:
  - validation

validate-all:
  stage: validation
  image: node:14-alpine
  script:
    - npm i pnpm -g
    - pnpm install

    - cd shared
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd backend
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - pnpm run test:e2e
    - cd ..

    - cd simulator
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..
