stages:
  - cache
  - validation

caching:
  stage: cache
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - Yellow
  only:
    refs:
      - web
    variables:
      - $docker == "cache"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile-cache
      --destination $CI_REGISTRY_IMAGE:cache

validate-all:
  stage: validation
  image: $CI_REGISTRY_IMAGE:cache
  tags:
    - Yellow
  script:
    - cp -r /tmp/.pnpm-store $(pwd)/.pnpm-store
    - pnpm config set store-dir $(pwd)/.pnpm-store
    - pnpm install -r

    - cd common-lib
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd ocpp-lib
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd csms-lib
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd csms-server
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - mkdir -p ../data && cp ../utils/certs/certificate.* ../data/
    - pnpm run test:e2e
    - cd ..

    - cd csms-server-ui
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd css-lib
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd css-ui
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..

    - cd css-cli
    - pnpm run lint
    - pnpm run build
    - pnpm run test
    - cd ..
