stages:
  - validation

shared:
  stage: validation
  image: node:14-alpine
  script:
    - cd shared
    - npm ci
    - npm run lint
    - npm run build
    - npm run test

backend:
  stage: validation
  image: node:14-alpine
  script:
    - cd shared
    - npm ci
    - npm run build
    - cd ../backend
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov
    - npm run test:e2e

simulator:
  stage: validation
  image: node:14-alpine
  script:
    - cd shared
    - npm ci
    - npm run build
    - cd ../simulator
    - npm ci
    - npm run lint
    - npm run build
    - npm run test
