FROM node:14-alpine

RUN mkdir -p /app
WORKDIR /app

RUN npm install pnpm -g

RUN mkdir -p client/ server/ shared/
COPY client/package.json ./client/
COPY server/package.json ./server/
COPY shared/package.json ./shared/

COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .

#RUN pnpm install
