FROM node:14-alpine

RUN mkdir -p \
  /builds/YellowGarbageBag/.pnpm-store \
  /builds/YellowGarbageBag/csms/simulator \
  /builds/YellowGarbageBag/csms/backend \
  /builds/YellowGarbageBag/csms/shared

WORKDIR /builds/YellowGarbageBag/csms

RUN npm install pnpm -g
RUN pnpm set verify-store-integrity false
RUN pnpm config set store-dir /builds/YellowGarbageBag/.pnpm-store

COPY simulator/package.json ./simulator/
COPY backend/package.json   ./backend/
COPY shared/package.json    ./shared/

COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .

RUN pnpm install
