FROM node:14-alpine

RUN apk --no-cache add curl

RUN curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
RUN pnpm config set store-dir /tmp/.pnpm-store

COPY .npmrc pnpm-lock.yaml ./

RUN pnpm fetch
